# Generated by Django 4.1 on 2022-08-29 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choice',
            new_name='Option',
        ),
        migrations.RenameField(
            model_name='option',
            old_name='choice',
            new_name='choice_text',
        ),
    ]
